export const elements = {
  navDate: document.querySelector('.nav__date'),
  skills: document.querySelector('.skills__icons'),
  popup: document.querySelector('.popup'),
  popupIcons: document.querySelector('.popup__icons'),
  popupAddIcon: document.querySelector('.skills__icon-add'),
  popupCloseBtn: document.querySelector('.popup__close-btn'),
  popupUpdateBtn: document.querySelector('.popup__add--btn'),
  popupSearch: document.querySelector('.search__input'),
  weekNumber: document.querySelector('.week__number'),
  weekDays: document.querySelector('.week-days'),
  weekNext: document.querySelector('.button__next--week'),
  weekPrevious: document.querySelector('.button__previous--week'),
  popupTask: document.querySelector('.popup-task'),
  popupTaskClose: document.querySelector('.popup-task__bg--close'),
  popupTaskForm: document.querySelector('.popup-task__form'),
  popupTaskText: document.querySelector('.popup-task__form--text'),
  sectionItem: document.querySelector('.section__item'),
  sections: document.querySelector('.sections'),
  sectionItemContent: document.querySelector('.section__item--content'),
  sectionItemInput: document.querySelector('.section__item--input'),
  month: document.querySelector('.month-name'),
  monthWeeks: document.querySelector('.month__weeks'),
  nextMonth: document.querySelector('.button__next--month'),
  previousMonth: document.querySelector('.button__previous--month'),
  year: document.querySelector('.year-number'),
  yearMonths: document.querySelector('.year__months'),
  nextYear: document.querySelector('.button__next--year'),
  previousYear: document.querySelector('.button__previous--year'),
  userIcon: document.querySelector('.nav__user'),
  userForm: document.querySelector('.nav__user--form')
}



